## copies pre-built projects to docker containers (via cmd: "nx docker-web ${app_name}" -> project.json)

FROM nginx:1.18-alpine AS base

COPY ./nginx.conf /etc/nginx/nginx.conf

FROM base AS deploy-app-001

COPY ./apps/app-001/web-build /frontend/build

FROM base AS deploy-app-002

COPY ./apps/app-002/web-build /frontend/build
