version: '3'
services:
  app-001:
    image: nx-reactnative-docker-app-001
    build:
      context: .
      dockerfile: Dockerfile.dockerbuild
      target: deploy-app-001
    ports:
      - 3001:80

  app-002:
    image: nx-reactnative-docker-app-002
    build:
      context: .
      dockerfile: Dockerfile.dockerbuild
      target: deploy-app-002
    ports:
      - 3002:80
